Spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:mysql://localhost:3306/case_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:p6spy:mysql://localhost:3306/case_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml

  freemarker:
    cache: false

