Spring:
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    #url: jdbc:mysql://localhost:3306/case_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    url: jdbc:p6spy:mysql://localhost:3306/case_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
  freemarker:
    cache: false
    settings:
      classic_compatible: true
  redis:
    host: localhost
    port: 6379
    password:
  data:
    elasticsearch:
      cluster-name: cq-elasticsearch
      cluster-nodes: localhost:9300
      repositories:
        enabled: true
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
mybatis-plus:
    mapper-locations: classpath*:/mapper/**Mapper.xml
file:
  upload:
    dir: ${user.dir}/upload
im:
  server:
    ip: localhost
    port: 9326

